n1 = int(input("Dame un número "))
n2 = int(input("Dame otro número "))
n3 = int(input("Ahora dame otro número "))
print ("El resultado de multiplicar el tercer número por la suma de los dos primeros es igual a: ", (n1+n2)*n3 )
print ("El resultado de multiplicar el primer número y el tercer número es: ", n1*n3 )
print ("El resultado de multiplicar el segundo número y el tercer número es: ", n2*n3 )